logdir: ./log/
tag: judge_train
model_dir: /storage/model/e2e_asr/wsj/supervised
model_name: e2e_si84
load_model_path: /storage/model/e2e_asr/wsj/supervised/e2e_si84
load_optimizer: True
dataset_root_dir: /storage/feature/wsj/processed/deltatrue
vocab_path: /storage/feature/wsj/processed/deltatrue/vocab_dict.pkl
non_lang_syms_path: /storage/feature/wsj/processed/deltatrue/non_lang_syms.pkl
summary_steps: 100
labeled_set: train_si84
unlabeled_set: train_si284
dev_set: test_dev93
test_set: test_eval92
max_feature_length: 2200
min_feature_length: 30
max_text_length: 220
min_text_length: 2
extra_length: 30
max_dec_timesteps: 230
batch_size: 16
shuffle: True
input_dim: 249
enc_hidden_dim: 320
enc_n_layers: 3
subsample: [2, 2, 2]
dropout_rate: 0.3
max_grad_norm: 5
dec_hidden_dim: 320
embedding_dim: 128
att_dim: 320
conv_channels: 10
conv_kernel_size: 100
att_odim: 320
heads: 1
init_tf_rate: 1.0
tf_rate_lowerbound: 0.6
tf_decay_epochs: 120
ls_weight: 0.05
weight_decay: 0.000001
gaussian_std: 0.075
add_gaussian: True
gaussian_epoch: 60
learning_rate: 0.0005
g_learning_rate: 0.0001
d_learning_rate: 0.0002
lr_gamma: 0.2
epochs: 300
judge_iterations: 30000
judge_share_param: True
judge_steps: 5
change_learning_rate_epoch: 50
