logdir: ./log/
tag: supervised
model_dir: /workspace/model/e2e_asr/
model_name: e2e_one_att_drop_sche_noshuf_cat_long.pkl
dataset_root_dir: /workspace/data/wsj/processed/
vocab_path: /workspace/data/wsj/processed/vocab_dict.pkl
non_lang_syms_path: /workspace/data/wsj/processed/non_lang_syms.pkl
max_kept: 20
summary_steps: 100
labeled_set: train_si84
unlabeled_set: train_si284
dev_set: test_dev93
max_feature_length: 1800
min_feature_length: 30
max_text_length: 210
min_text_length: 2
max_dec_timesteps: 220
batch_size: 24
shuffle: True
input_dim: 83
enc_hidden_dim: 320
enc_n_layers: 3
subsample: [2, 2, 2]
dropout_rate: 0.3
max_norm: 2
dec_hidden_dim: 512
embedding_dim: 128
att_dim: 320
conv_channels: 10
conv_kernel_size: 100
att_odim: 320
heads: 1
init_tf_rate: 1.0
learning_rate: 0.0005
lr_gamma: 0.0001
epochs: 300
change_learning_rate_epoch: 50
