logdir: ./log/
tag: supervised
model_dir: /storage/model/e2e_asr/wsj/supervised/
model_name: e2e.pkl
dataset_root_dir: /storage/feature/wsj/processed/
vocab_path: /storage/feature/wsj/processed/vocab_dict.pkl
non_lang_syms_path: /storage/feature/wsj/processed/non_lang_syms.pkl
max_kept: 20
summary_steps: 100
labeled_set: train_si84
unlabeled_set: train_si284
dev_set: test_eval92
max_feature_length: 1600
min_feature_length: 30
max_text_length: 200
min_text_length: 2
max_dec_timesteps: 200
batch_size: 2
shuffle: False
input_dim: 83
enc_hidden_dim: 1024
enc_n_layers: 2
subsample: [2, 2]
dropout_rate: 0.3
dec_hidden_dim: 1024
att_dim: 1024
conv_channels: 10
conv_kernel_size: 201
att_odim: 1024
heads: 4
init_tf_rate: 1.0
learning_rate: 0.0005
epochs: 20
