logdir: ./log/
tag: supervised
model_dir: /workspace/model/e2e_asr/
model_name: e2e_two_layers.pkl
dataset_root_dir: /workspace/data/wsj/processed/
vocab_path: /workspace/data/wsj/processed/vocab_dict.pkl
non_lang_syms_path: /workspace/data/wsj/processed/non_lang_syms.pkl
max_kept: 20
summary_steps: 100
labeled_set: train_si84
unlabeled_set: train_si284
dev_set: test_eval92
max_feature_length: 1400
min_feature_length: 30
max_text_length: 170
min_text_length: 2
max_dec_timesteps: 200
batch_size: 16
shuffle: False
input_dim: 83
enc_hidden_dim: 320
enc_n_layers: 2
subsample: [2, 2]
dropout_rate: 0.3
dec_hidden_dim: 320
embedding_dim: 128
att_dim: 320
conv_channels: 10
conv_kernel_size: 100
att_odim: 320
heads: 4
init_tf_rate: 1.0
learning_rate: 0.001
epochs: 200
